[versions]
# App Versions
app = "0.1"
versioncode = "1"

java-toolchain = "17"

android-gradle-plugin = "8.13.2"

androidx-appcompat = "1.7.1"
androidx-activity-compose = "1.12.4"
androidx-browser = "1.9.0"
androidx-core = "1.17.0"
androidx-datastore = "1.2.0"
androidx-hilt = "1.3.0"
androidx-hilt-navigation-compose = "1.3.0"
androidx-lifecycle = "2.10.0"
androidx-material-icons = "1.7.8"
androidx-work = "2.11.1"

circuit = "0.33.0"

coil = "2.7.0"

compose-bom = "2025.12.01"

dagger = "2.58"

desugared-jdk-libs = "2.1.5"

firebase-bom = "34.9.0"
firebase-crashlytics-plugin = "3.0.6"

google-services = "4.4.4"

junit = "4.13.2"

kotest = "6.1.3"

kotlin = "2.3.10"

kotlinx = "1.10.2"
kotlinx-collections-immutable = "0.4.0"
kotlinx-serialization-json = "1.10.0"
kotlinx-datetime = "0.7.1"

ksp = "2.3.6"

ktlint-compose-rules = "0.4.27"

material = "1.13.0"

muzei-api = "3.4.2"

okhttp = "5.3.2"

retrofit = "3.0.0"
retrofit-kotlinx-serialization-converter = "1.0.0"

spotless = "8.1.0"

turbine = "1.2.1"


[libraries]
androidx-appcompat = { module = " androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-core", version.ref = "androidx-material-icons" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

androidx-datastore = { module = "androidx.datastore:datastore-core", version.ref = "androidx-datastore" }

androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }

androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidx-hilt" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }

dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }

material = { module = "com.google.android.material:material", version.ref = "material" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }

android-desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugared-jdk-libs" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }

junit = { module = "junit:junit", version.ref = "junit" }
kotest = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

muzei-api = { module = "com.google.android.apps.muzei:muzei-api", version.ref = "muzei-api" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-kotlinx-serialization-converter" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }

coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

circuit = { module = "com.slack.circuit:circuit-foundation", version.ref = "circuit" }
circuit-codegen-annotations = { module = "com.slack.circuit:circuit-codegen-annotations", version.ref = "circuit" }
circuit-codegen = { module = "com.slack.circuit:circuit-codegen", version.ref = "circuit" }
circuitx = { module = "com.slack.circuit:circuitx-android", version.ref = "circuit" }
circuit-test = { module = "com.slack.circuit:circuit-test", version.ref = "circuit" }

# Linting
ktlint-compose-rules = { group = "io.nlopez.compose.rules", name = "ktlint", version.ref = "ktlint-compose-rules" }

# Dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-compose-gradle-plugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
spotless-gradle-plugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "ksp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[bundles]
testing-unit = [
    "junit",
    "kotest",
    "kotest-property",
    "kotlinx-coroutines-test",
    "turbine",
]
firebase = [
    "firebase-analytics",
    "firebase-crashlytics"
]